FROM quay.io/centos/centos:stream9

ENV PKGS_LIST=packages-list.okd
ARG EXTRA_PKGS_LIST
ARG PATCH_LIST

COPY ${PKGS_LIST}* ${EXTRA_PKGS_LIST:-$PKGS_LIST} ${PATCH_LIST:-$PKGS_LIST} /tmp/
COPY prepare-image.sh patch-image.sh /bin/

# Configure OpenStack repos from RDO https://www.rdoproject.org
RUN dnf upgrade -y && \
  dnf install -y dnf-plugins-core && \
  dnf config-manager --enable crb && \
  curl https://trunk.rdoproject.org/centos9-master/puppet-passed-ci/delorean.repo -o /etc/yum.repos.d/rdo.repo && \
  curl https://trunk.rdoproject.org/centos9-master/delorean-deps.repo -o /etc/yum.repos.d/rdo-deps.repo

RUN prepare-image.sh && \
  mkdir -p /etc/ironic-python-agent && \
  rm -f /bin/prepare-image.sh

COPY hardware_manager /tmp/hardware_manager

RUN PBR_VERSION=1.0 pip3 install --no-index --verbose --prefix=/usr /tmp/hardware_manager

COPY ironic-python-agent.conf /etc/ironic-python-agent/00-defaults.conf

ENTRYPOINT ["ironic-python-agent", "--config-dir", "/etc/ironic-python-agent"]
