FROM quay.io/centos/centos:stream9

ENV PKGS_LIST=packages-list.okd
ARG EXTRA_PKGS_LIST
ARG PATCH_LIST

COPY ${PKGS_LIST}* ${EXTRA_PKGS_LIST:-$PKGS_LIST} ${PATCH_LIST:-$PKGS_LIST} python-requirements.okd /tmp/
COPY prepare-image.sh patch-image.sh setup.okd /bin/

# Install Python 3.12 for OKD builds
RUN dnf upgrade -y && \
  dnf install -y git python3.12 python3.12-devel

COPY hardware_manager /tmp/hardware_manager

RUN prepare-image.sh && \
  mkdir -p /etc/ironic-python-agent && \
  rm -f /bin/prepare-image.sh

COPY ironic-python-agent.conf /etc/ironic-python-agent/00-defaults.conf

ENTRYPOINT ["ironic-python-agent", "--config-dir", "/etc/ironic-python-agent"]
