#!/bin/bash

cat > /etc/ironic-python-agent/ironic-python-agent.conf <<EOF
[DEFAULT]
debug = True
log-file = /var/log/ironic-python-agent.log
use_stderr = True
EOF

ARGS=
if [[ -f "/etc/ironic-python-agent/ignition.conf" ]]; then
    ARGS="--config-file /etc/ironic-python-agent/ignition.conf"
fi

exec ironic-python-agent \
    --config-file /etc/ironic-python-agent/ironic-python-agent.conf $ARGS
